[package]
name = "simple-redis"
version = "0.1.0"
authors = ["Nassim <jr_zorgani@esi.dz>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "simple-redis"

[dependencies]
libc = "0.2.144"
tokio = { version = "1.23.0", features = ["full"] } # async networking
